version: '3.8'
services:
  aco-api:
    build: ./backend
    container_name: aco-api
    ports:
      - "8081:8081"
    restart: always

  aco-web:
    image: nginx:alpine
    container_name: aco-web
    ports:
      - "80:80" # Cổng mặc định để truy cập web
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: always